name: amy-server

services:
  release-server:
    container_name: amy-server
    image: amy-server:latest
    ports:
      - "8090:8080"
      - "5006:5006"
    restart: unless-stopped

    environment:
      - DATASOURCE_HOST=192.168.31.114
      - DATASOURCE_PORT=3306
      - DATASOURCE_NAME=amy
      - DATASOURCE_USERNAME=amydb
      - DATASOURCE_PASSWORD=sEQ1iqArgC7ZmlJ7z
      - REDIS_HOST=192.168.31.114
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=