spring:
  datasource:
    url: jdbc:mariadb://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_NAME}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DB}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms


jwt:
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 7200000
  # token 续期检查时间范围（默认30分钟，单位默认毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认 1小时，这里单位毫秒
  renew: 3600000

login:
  single-login: true

static-resource-directory-properties:
  user-avatar-directory: /amy/user-avatar
  user-avatar-path-prefix: /resource/user-avatar
  artist-avatar-directory: /amy/artist-avatar
  artist-avatar-path-prefix: /resource/artist-avatar
  video-roots:
    - { name: 'no.1', path: /amy/video_1 }
  enable-video-root: 'no.1'
  video-resource-prefix: /resource/video
  upload-temp-directory: /amy/temp
  poster-path-prefix: /resource/poster
  poster-directory: /amy/poster

ffmpeg:
  ffprobe-executor-path: ffprobe
  ffmpeg-executor-path: ffmpeg
  conversion-to-mp4-args: "-y -c:v h264_qsv -preset medium -crf 10 -c:a aac -b:a 320k"
  conversion-to-ts-args: "-y -vcodec copy -acodec copy"
  video-encoder: h264_qsv
  audio-encoder: aac