spring:
  datasource:
    url: jdbc:mariadb://47.112.7.167:3306/amy_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: amy_dev
    password: Mi3Msda457AmSp2w

  data:
    redis:
      host: 47.112.7.167
      port: 6379
      timeout: 5000ms
      database: 0
      password: redis_Sx5DsW
      lettuce:
        pool:
          # 最大连接数（默认8）
          max-active: 8
          # 最大空闲连接（默认8）
          max-idle: 8
          # 最小空闲连接（默认0）
          min-idle: 2
          # 最大等待时间（获取连接时的最长等待时间，单位毫秒，-1表示无限制）
          max-wait: 1000ms


jwt:
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认2小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 7200000
  # token 续期检查时间范围（默认30分钟，单位默认毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认 1小时，这里单位毫秒
  renew: 3600000

static-resource-directory-properties:
  user-avatar-directory: C:\Users\ayuan\Documents\AMY\static\user-avatar
  user-avatar-path-prefix: /resource/user-avatar
  artist-avatar-directory: C:\Users\ayuan\Documents\AMY\static\artist-avatar
  artist-avatar-path-prefix: /resource/artist-avatar
  video-roots:
    - { name: 'no.1', path: C:\Users\ayuan\Documents\AMY\static\video }
  enable-video-root: 'no.1'
  video-resource-prefix: /resource/video
  upload-temp-directory: C:\Users\ayuan\Documents\AMY\static\temp
  poster-directory: C:\Users\ayuan\Documents\AMY\static\poster
  poster-path-prefix: /resource/poster

ffmpeg:
  ffmpeg-executor-path: D:\workspace\resource\ffmpeg-n8.0-latest-win64-gpl-8.0\bin\ffmpeg.exe
  ffprobe-executor-path: D:\workspace\resource\ffmpeg-n8.0-latest-win64-gpl-8.0\bin\ffprobe.exe
  conversion-to-mp4-args: "-y -c:v h264_amf -preset medium -crf 10 -c:a aac -b:a 320k"
  conversion-to-ts-args: "-y -vcodec copy -acodec copy"
  conversion-to-m3u84k-args: "-y -vf scale=3840:2160:force_original_aspect_ratio=decrease,pad=3840:2160:(ow-iw)/2:(oh-ih)/2 -c:v h264_amf -b:v 15000k -g 48 -sc_threshold 0 -c:a aac -b:a 128k -hls_time 6 -hls_playlist_type vod -hls_segment_filename "
  conversion-to-m3u82k-args: "-y -vf scale=2560:1440:force_original_aspect_ratio=decrease,pad=2560:1440:(ow-iw)/2:(oh-ih)/2 -c:v h264_amf -b:v 8000k -g 48 -sc_threshold 0 -c:a aac -b:a 128k -hls_time 6 -hls_playlist_type vod -hls_segment_filename "
  conversion-to-m3u81080p-args: "-y -vf scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2 -c:v h264_amf -b:v 5000k -g 48 -sc_threshold 0 -c:a aac -b:a 128k -hls_time 6 -hls_playlist_type vod -hls_segment_filename "
  conversion-to-m3u8720p-args: "-y -vf scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2 -c:v h264_amf -b:v 2500k -g 48 -sc_threshold 0 -c:a aac -b:a 128k -hls_time 6 -hls_playlist_type vod -hls_segment_filename "
  conversion-to-m3u8480p-args: "-y -vf scale=854:480:force_original_aspect_ratio=decrease,pad=854:480:(ow-iw)/2:(oh-ih)/2 -c:v h264_amf -b:v 1200k -g 48 -sc_threshold 0 -c:a aac -b:a 128k -hls_time 6 -hls_playlist_type vod -hls_segment_filename "